name: 'Chromatic'

on: push

permissions:
  contents: read

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install
        uses: ./.github/composite-actions/install
      - name: Publish to Chromatic
        uses: chromaui/action@8d925269a481085d451544f6bd9aa2ab3af55b5d # v16.9.1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          skip: 'renovate/**'
          workingDir: packages/arte-odyssey
